# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 老李的杂货铺
email: don.anthony.lee@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  无鱼虾亦可
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://donanthonylee.github.io" # the base hostname & protocol for your site
#twitter_username: none
github_username:  DonAnthonyLee

# Build settings
markdown: kramdown

theme: jekyll-theme-leap-day